# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-28 17:56
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0013_remove_makale_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makale',
            options={'ordering': ['-publishing_date', 'id']},
        ),
        migrations.AddField(
            model_name='makale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='makales', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='makale',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
    ]
