# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-28 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20200328_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makale',
            old_name='slug',
            new_name='slug2',
        ),
    ]
