# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-28 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20200328_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makale',
            options={'ordering': ['-publishing_date2', 'id']},
        ),
        migrations.RenameField(
            model_name='makale',
            old_name='content',
            new_name='content2',
        ),
        migrations.RenameField(
            model_name='makale',
            old_name='publishing_date',
            new_name='publishing_date2',
        ),
        migrations.RenameField(
            model_name='makale',
            old_name='title',
            new_name='title2',
        ),
        migrations.RenameField(
            model_name='makale',
            old_name='user',
            new_name='user2',
        ),
    ]
