# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-28 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20200328_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makale',
            name='user2',
        ),
        migrations.DeleteModel(
            name='Makale',
        ),
    ]
